### ISSUE TITLE
Draw a model story board for client app

### ISSUE THREAD

**Issue by sparklingcoast** [JakeNarkizian/sound-send#29]
I will add a label to the empty view that displays "Soundsend". I will also add a "Create Channel" button that when pressed, will go to a different screen containing a (for now empty) listview and a for now static placeholder label representing some identifier of the channel. There will be another button, a "Join Channel" button that, when pressed, will go to a different screen containing another empty listview. The listviews will be filled out in #17, but this issue deals with the UI around them.

**Comment by nsjake** [comment]
@bluesnowstorm can you expand on this more here? Does this issue call for concept art? Code in the iOS project? Please add what specifically a commit addressing this issue would do.

**Comment by nsjake** [comment]
Please note that issues #11 and #17 are dependent on this issue for the following reasons:
- #11 needs to know what data they need to send to UI elements 
- #17 needs to know what data will be in each cell of the listview

**Comment by nsjake** [comment]
@bluesnowstorm please remember to update your comment before you start working on this issue.

**Comment by sparklingcoast** [comment]
![prototypeuidesign](https://cloud.githubusercontent.com/assets/22828963/19713533/b39d2c9a-9afb-11e6-9b4d-0db96e210a45.png)

**Comment by nsjake** [comment]
@bluesnowstorm 
**"I will also add a "Create Channel" button that when pressed, will go to a different screen containing a (for now empty) listview"**

Why a list view for channel creation? 

**"and a for now static placeholder label representing some identifier of the channel."**

Can you document (in a comment on this ticket) what specifically these label elements will convey to the user? Tag the iOS team so that they know for #11 

**"There will be another button, a "Join Channel" button that, when pressed, will go to a different screen containing another empty listview. The listviews will be filled out in #17, but this issue deals with the UI around them."**

I think you still don't understand the relationship between these two issues. The list view will be filled out by #17 but this issue should convey to the assignee of #17 what _specifically_ the list view they are implementing needs to display. Please add that also this information as a separate comment on this issue and tag the assignee of #17. 

In a sense you are writing the UX for the app, a bunch of placeholder UIView elements are not enough for this task.

**Comment by nsjake** [comment]
@bluesnowstorm also if you would like to break up the model of the UI (e.g. one drawn on paint or something) and implementing this UI on the storyboard that might be a good idea but I'lll leave that decision up to you.

**Comment by nsjake** [comment]
Per Arnav and I's private discussion this is the scope of this issue:

Create a visual diagram of the specifics of every component of the UI of the app. We need to know what every part of the app will look like and what information is required for each view of the app. Arnav has agreed to list out this information per blocked tickets #11 and #17 and tag the relevant team members. This ticket should be addressed before the end of this week so that the client-side team can start their respective tickets.
