### ISSUE TITLE
Handle active channel info requests

### ISSUE THREAD

**Issue by nsjake** [JakeNarkizian/sound-send#34]
We need a static URL that serves info about all the current channels. This is related to #17.

**Comment by nsjake** [comment]
This should not be started until #13 is completed.

**Comment by seant2g0** [comment]
hey this is from the scrum meeting

TableController.swift: This code is what we wrote for the listview. We
got it from the following tutorial
http://www.kaleidosblog.com/swift-uitableview-load-data-from-json

I had to delete the creating a view part of the section because i was
trying to debug. So you'll have to do those steps again.

connect.swift: This contains the code from the http request
we got it from the following tutorial:
http://www.kaleidosblog.com/nsurlsession-in-swift-get-and-post-data

And you can't see it in xcode but when you look in the folder, there's
also a Nocilla folder, Podfile.lock file, and Podfile file. Those are
all part of the stubbing feature provided by Nocilla's Mock Server.
Documentation is at this link:
https://github.com/luisobo/Nocilla

We're currently trying to figure out how to integrate Nocilla's tests
into the testing framework already present in Xcode

Let me know if you have any questions!

**Comment by seant2g0** [comment]
JSON format:

{ {name: <string>, description: <string>}, {name: <string>, description: <string>}, {name: <string>, description: <string>}, ... }

Example JSON:

{ { name: "user1", description: "first description" }, { name: "user2", description: "second description" },  { name: "user3", description: "third description" } }

**Comment by nsjake** [comment]
@seant2g0 Thanks for starting this. The JSON scheme you proposed is not valid. You are encapsulating a list of users in a JSON object. This needs to be a list. The keys to the nested objects also need to be string literals. Also I know @bluesnowstorm added the description to the UI model but I think at this point it is redundant as names can be pretty descriptive. I counter-propose this scheme:

```
["channel 1", "channel 2"]
```

Just the names in a simple list.
